<?php

$pertanyaan_setuju = [
    "Saya mempersiapkan diri sebelum mengikuti kelas.",    
    "Saya merasa bertanggung jawab atas hasil belajar saya sendiri.",        
    "Saya berusaha keras untuk memahami materi perkuliahan.",          
    "Semester ini menantang saya untuk belajar lebih keras dari yang saya kira.",                
    "Saya merasa memiliki strategi belajar yang efektif.",          
    "Bahan ajar yang diberikan meningkatkan pengetahuan dan keterampilan saya.",          
    "Semester ini membuat saya semakin tertarik belajar Psikologi.",                
    "Mata kuliah di semester ini membuat saya semakin percaya diri untuk mengembangkan diri dalam bidang Psikologi.",  
    "Beban materi, tugas, dan ujian di semester ini sesuai dengan SKS.",    
    "Tugas dan ujian sudah secara tepat menilai apa yang telah saya pelajari dalam mata kuliah.",       
    "Tugas dan ujian mencerminkan isi mata kuliah.",         
    "Tugas dan ujian saya dinilai secara adil.",                
    "Penilaian tugas dan ujian dilakukan secara jelas dan transparan.",   
    "Tugas dan ujian mata kuliah serta materi perkuliahan saling melengkapi satu sama lain.",   
    "Dosen mempersiapkan kelas dengan baik, memberikan kuliah dengan teratur dan memanfaatkan waktu dengan maksimal.",        
    "Dosen menyampaikan materi dan tugas secara jelas dan mudah dimengerti.",          
    "Metode pengajaran yang diberikan membuat saya tertarik untuk belajar.",                
    "Dosen memberikan masukan terhadap tugas dan/atau ujian saya.",  
    "Dosen responsif ketika mahasiswa bertanya atau membutuhkan bantuan.",   
    "Asmatkul/mentor memahami materi perkuliahan yang diasisteni.",        
    "Saya merasa nyaman mengajukan pertanyaan kepada asmatkul/mentor.",          
    "Asmatkul/mentor bersedia menjawab pertanyaan.",                
    "Secara keseluruhan, asmatkul/mentor bekerja dengan baik.",    
    "Asmatkul/mentor fleksibel dan dapat menyesuaikan lingkungan belajar ketika ada yang tidak berjalan sesuai rencana.",  
    "Pengalaman berguna.",        
    "Mendapat keterampilan tambahan.",          
    "Terlalu melelahkan.",                
    "Tugas lain jadi menumpuk.", 
    "Ingin gajinya saja.",     
    "Kesempatan untuk menonjolkan diri di depan adik angkatan.",   
    "Pembuktian bahwa saya lebih baik dari mahasiswa lain.",        
    "Tidak ingin jadi asmatkul/mentor lagi.",          
    "Mahasiswa aktif di kelas/platform ajar.",                
    "Komunikasi dengan mahasiswa lancar.",   
    "Mahasiswa memakai banyak alasan untuk tidak mengerjakan tugasnya.",      
    "Mahasiswa kurang berusaha untuk memahami materi belajar.",    
    "Mahasiswa kurang mampu memahami materi belajar.",        
    "Motivasi belajar mahasiswa rendah.",          
    "Jumlah mahasiswa terlalu banyak untuk kapasitas saya.",                
    "Komunikasi kami lancar.",   
    "Kami dapat bekerja sama dengan baik.",     
    "Kami tidak kompak.",    
    "Jumlah asmatkul/mentor perlu ditambah.",        
    "Komunikasi dengan dosen lancar.",          
    "Penjelasan dosen mudah dipahami.",                
    "Dosen responsif dalam menanggapi.",     
    "Dosen cuek dengan mahasiswa.",     
    "Dosen memberi terlalu banyak tugas.",    
    "Pengalaman berguna.",        
    "Mendapat keterampilan tambahan.",          
    "Terlalu melelahkan.",                
    "Tugas lain jadi menumpuk.",   
    "Ingin gajinya saja.",     
    "Kesempatan untuk berprestasi.",    
    "Pembuktian bahwa saya lebih baik dari mahasiswa lain.",        
    "Ingin mengikuti program MBKM lagi.",          
    "Mitra memberikan ruang dan kesempatan untuk belajar.",                
    "Mitra memberikan supervisor yang profesional.",   
    "Mitra memberikan beban kerja sesuai ketentuan program MBKM.",     
    "Mitra memberikan rasa nyaman dan aman.",    
    "Mitra dapat diajak berkomunikasi.",        
    "Mitra menerima mahasiswa dengan terbuka.",          
    "Mitra membimbing mahasiswa dengan profesional.",                
    "Mitra memberikan peluang karier yang menjanjikan.", 
    "Supervisor mampu diajak berkomunikasi.",     
    "Supervisor memberikan bimbingan dengan maksimal.",    
    "Supervisor responsif dalam membantu saya.",        
    "Supervisor memberikan umpan balik terhadap kinerja saya.",          
    "Dosen mampu diajak berkomunikasi.",                
    "Dosen memberikan bimbingan dengan maksimal.",   
    "Dosen responsif dalam membantu saya.",     
    "Dosen memberikan umpan balik terhadap kinerja saya."   
];

$pertanyaan_komentar = [
    1 => "Hal lain yang ingin disampaikan:",
    2 => "Hal lain yang ingin disampaikan:",
    3 => "Apakah ada masukan khusus tentang asmatkul/mentor yang ingin kamu soroti?",
    4 => "Masukan untuk mata kuliah PPH",
    5 => "Sebutkan setidaknya 1 perubahan yang bisa dilakukan oleh dosen untuk membantumu meningkatkan hasil belajar.",
    6 => "Apa kelebihan, manfaat atau pengalaman positif yang kamu peroleh selama semester ini?",
    7 => "Apakah ada kritik yang ingin kamu berikan kepada dosen, prodi, fakultas, atau universitas?",
    8 => "Pengalaman positifmu selama semester ini, termasuk jika kamu ingin memberi apresiasi kepada dosen/asisten mata kuliah:",
    9 => "Hal lain yang ingin disampaikan:",
    10 => "Hal lain yang ingin disampaikan:",
    11 => "Masukan untuk pelaksanaan PPP:",
    12 => "Masukan untuk pelaksanaan Ujian PPP:",
    13 => "Masukan untuk pelaksanaan Tugas Akhir:",
    14 => "Masukan untuk pelaksanaan Ujian Hasil Penelitian:",
    15 => "Silakan berikan dukungan kepada teman-teman mahasiswa yang lain.",
    16 => "Masukan bagi Unit Penjaminan Mutu:",
    17 => "Apakah kamu mengetahui jika kamu atau temanmu membutuhkan layanan kesehatan mental? Jika iya, tulis nama dan NIM kamu atau temanmu.",
    18 => "Jenis layanan kesehatan mental apa yang dibutuhkan?",
];

$tambahan = ['usaha_puas_1', 'hasil_puas_1', 'efektivitas_1', 'efektivitas_2', 'efektivitas_3', 'mentor', 'MBKM_1', 'MBKM_2', 'PPP', 'TA'];

$tambahan_deskripsi = [
    'usaha_puas_1' => "Seberapa puas saya dengan usaha yang telah saya keluarkan di semester ini?",
    'hasil_puas_1' => "Seberapa puas saya dengan hasil yang saya dapatkan di semester ini?",
    'efektivitas_1' => "Seberapa efektif proses perkuliahan yang telah berjalan di Semester Ganjil 24/25?",
    'efektivitas_2' => "Seberapa baik proses pemberian nilai di Semester Ganjil 24/25?",
    'efektivitas_3' => "Seberapa berhasil dosen dalam menciptakan lingkungan yang kondusif untuk belajar?",
    'mentor' => "Apakah kamu asmatkul/mentor di semester ini?",
    'MBKM_1' => "Apakah kamu mengikuti Program MBKM di Semester Ganjil 24/25?",
    'MBKM_2' => "Program MBKM yang kamu ikuti di Semester Ganjil 24/25:",
    'PPP' => "Apakah kamu mengikuti kelas PPP di Semester Ganjil 24/25?",
    'TA' => "Apakah kamu mengikuti Tugas Akhir di Semester Ganjil 24/25?"
];
?>